// Generated by scripts/generate-listening-audio.mjs.
export const listeningAudioManifest: Record<string, { duration: number; turns: { startTime: number; endTime: number }[] }> = {
  "toefl-conversation-research-project": {
    "duration": 181.159,
    "turns": [
      {
        "startTime": 0,
        "endTime": 20.332
      },
      {
        "startTime": 20.632,
        "endTime": 35.3
      },
      {
        "startTime": 35.6,
        "endTime": 53.406
      },
      {
        "startTime": 53.706,
        "endTime": 71.671
      },
      {
        "startTime": 71.971,
        "endTime": 89.671
      },
      {
        "startTime": 89.971,
        "endTime": 108.628
      },
      {
        "startTime": 108.928,
        "endTime": 117.358
      },
      {
        "startTime": 117.658,
        "endTime": 134.108
      },
      {
        "startTime": 134.408,
        "endTime": 143.73
      },
      {
        "startTime": 144.03,
        "endTime": 158.817
      },
      {
        "startTime": 159.117,
        "endTime": 172.84
      },
      {
        "startTime": 173.14,
        "endTime": 181.159
      }
    ]
  },
  "toefl-conversation-library-exhibit": {
    "duration": 178.028,
    "turns": [
      {
        "startTime": 0,
        "endTime": 13.963
      },
      {
        "startTime": 14.263,
        "endTime": 29.861
      },
      {
        "startTime": 30.161,
        "endTime": 40.294
      },
      {
        "startTime": 40.594,
        "endTime": 54.943
      },
      {
        "startTime": 55.243,
        "endTime": 66.426
      },
      {
        "startTime": 66.726,
        "endTime": 83.92
      },
      {
        "startTime": 84.22,
        "endTime": 97.305
      },
      {
        "startTime": 97.605,
        "endTime": 115.065
      },
      {
        "startTime": 115.365,
        "endTime": 124.847
      },
      {
        "startTime": 125.147,
        "endTime": 139.894
      },
      {
        "startTime": 140.194,
        "endTime": 147.654
      },
      {
        "startTime": 147.954,
        "endTime": 165.92
      },
      {
        "startTime": 166.22,
        "endTime": 178.028
      }
    ]
  },
  "toefl-lecture-urban-heat": {
    "duration": 236.478,
    "turns": [
      {
        "startTime": 0,
        "endTime": 33.005
      },
      {
        "startTime": 33.555,
        "endTime": 66.68
      },
      {
        "startTime": 67.23,
        "endTime": 102.177
      },
      {
        "startTime": 102.727,
        "endTime": 136.091
      },
      {
        "startTime": 136.642,
        "endTime": 171.256
      },
      {
        "startTime": 171.806,
        "endTime": 205.902
      },
      {
        "startTime": 206.452,
        "endTime": 236.478
      }
    ]
  },
  "toefl-lecture-retrieval-practice": {
    "duration": 238.752,
    "turns": [
      {
        "startTime": 0,
        "endTime": 28.617
      },
      {
        "startTime": 29.167,
        "endTime": 60.231
      },
      {
        "startTime": 60.781,
        "endTime": 97.124
      },
      {
        "startTime": 97.674,
        "endTime": 133.977
      },
      {
        "startTime": 134.527,
        "endTime": 169.554
      },
      {
        "startTime": 170.104,
        "endTime": 205.024
      },
      {
        "startTime": 205.574,
        "endTime": 238.752
      }
    ]
  },
  "toefl-lecture-pottery-trade": {
    "duration": 239.816,
    "turns": [
      {
        "startTime": 0,
        "endTime": 31.476
      },
      {
        "startTime": 32.026,
        "endTime": 64.247
      },
      {
        "startTime": 64.797,
        "endTime": 95.661
      },
      {
        "startTime": 96.211,
        "endTime": 134.336
      },
      {
        "startTime": 134.886,
        "endTime": 166.894
      },
      {
        "startTime": 167.444,
        "endTime": 202.112
      },
      {
        "startTime": 202.662,
        "endTime": 239.816
      }
    ]
  },
  "toefl-lecture-exoplanets": {
    "duration": 244.47,
    "turns": [
      {
        "startTime": 0,
        "endTime": 30.04
      },
      {
        "startTime": 30.59,
        "endTime": 68.103
      },
      {
        "startTime": 68.653,
        "endTime": 99.996
      },
      {
        "startTime": 100.546,
        "endTime": 134.562
      },
      {
        "startTime": 135.112,
        "endTime": 172.439
      },
      {
        "startTime": 172.989,
        "endTime": 206.46
      },
      {
        "startTime": 207.01,
        "endTime": 244.47
      }
    ]
  }
};
